server:
  port: 8080
  servlet:    context-path: /sagi
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sagi_inventario?useSSL=false&useTimezone=true&serverTimezone=America/Bahia
    username: root
    password: eloah1106
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:      ddl-auto: update
app:
  url: http://localhost:${server.port}
  SENDGRID_API_KEY: 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
